### ISSUE TITLE
Publishing checklist

### ISSUE THREAD

**Issue by oesgalha** [instruct-br/nameko-reloader#1]
Ok, here are some items to complete in order to publish the package.

- [x] Remove the lockfile from version control
- [x] Translate code comments
- [x] Translate and review the README
- [x] Include a workflow to build and publish the package

## Remove the lockfile from version control

Since this is a library, add the `.lock` file to .gitinore.

From Poetry docs:

> For libraries it is not necessary to commit the lock file.

https://python-poetry.org/docs/basic-usage/#commit-your-poetrylock-file-to-version-control

---

Here is another source about when you should keep lockfiles in (or out) of version control:
https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

## Translate code comments

Translate the docstrings and comments at `~/nameko_reloader/nameko_reloader.py` to english.

## Translate and review the README

The README in this repository will be available as the "Project description" at PyPI website. Translate it to english and add a minimal documentation:

- [x] A beginning section with a summary describing the package purpose
- [x] A usage section explaining how to use it in your project

See `nameko-vault`:
- https://github.com/instruct-br/nameko-vault
- https://pypi.org/project/nameko-vault/

## Include a workflow to build and publish the package

Copy the workflow from here:
https://github.com/instruct-br/nameko-vault/blob/master/.github/workflows/ci.yml

**Comment by oesgalha** [comment]
See #3

**Comment by oesgalha** [comment]
Closed by #2 and #4
